### PR TITLE
Enabled CMSG_MOUNTSPECIAL_ANIM for 5.4.8

### PR DESCRIPTION
**Pull request by wowharley**
SMSG_MOUNTSPECIAL_ANIM is already enabled and structure and value is already updated

### CODE REVIEW

**Comment by wowharley** [comment]
adding more pull request until its merged.

**Comment by Bodeguero** [comment]
**@wowharley  and @Mysterium So sending PR without testing? Where's statement? Before sending any PR please test before!** 


`/home/travis/build/JadeCore/JadeCore/src/server/game/Server/Protocol/Opcodes.cpp: In member function ‘void OpcodeTable::InitializeClientTable()’:
/home/travis/build/JadeCore/JadeCore/src/server/game/Server/Protocol/Opcodes.cpp:241:27: error: ‘CMSG_MOUNTSPECIAL_ANIM’ was not declared in this scope
     DEFINE_OPCODE_HANDLER(CMSG_MOUNTSPECIAL_ANIM,                         0x0082, STATUS_LOGGEDIN,  PROCESS_THREADUNSAFE, &WorldSession::HandleMountSpecialAnimOpcode       ); // 5.4.8 18414
                           ^
/home/travis/build/JadeCore/JadeCore/src/server/game/Server/Protocol/Opcodes.cpp:63:65: note: in definition of macro ‘DEFINE_OPCODE_HANDLER’
     ValidateAndSetOpcode<(opcodeNumber < NUM_OPCODE_HANDLERS), (opcode != 0)>(opcode, opcodeNumber, #opcode, status, processing, handler);`

**Comment by wowharley** [comment]
i know i dont have control to pull request or i would of waited
i will fix the issue with the opcodes

**Comment by Bodeguero** [comment]
@wowharley Of course you have control of PR, just make the changes test it locally and then send it!

If sending PR without doing the test before I will not accept!

Gratful!

**Comment by wowharley** [comment]
another PR was added to fix the compile, sorry about that i was afk when travis was doing its magic

**Pull request merged**
