### PR TITLE
Update Boss Blade Lord Tayak - Phase

### PR DESCRIPTION
**Pull request by rec0d**
phase added

### CODE REVIEW

**Comment by Bodeguero** [comment]
@rec0d Place the information in this PR, the next time you send out information I will cancel and close!

**Comment by rec0d** [comment]
PR? pull requests? thats what i did?

**Comment by Bodeguero** [comment]
@rec0d Yes man!

**Comment by cybrann** [comment]
I will not merge this because this is just copied from the 5.4.7 source. Mostly every script there was hacky.

**Comment by Bodeguero** [comment]
@cybrann I can close or yourself closes?

🤓

**Comment by wowharley** [comment]
You should close it, no effort to change any of the string when he port things over. This is just copy and paste

**Pull request closed without merging**
