### PR TITLE
[Core/Opcodes] Enabled CMSG_CHANNEL_ and SMSG_SET_PHASE_SHIFT opcodes to 5.4.8

### PR DESCRIPTION
**Pull request by wowharley**

### CODE REVIEW

**Comment by wowharley** [comment]
Issue fixed for last PR

**Comment by Bodeguero** [comment]
@wowharley I do not see any updates - can show me what you found opcode?

Gratful

**Comment by wowharley** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/blob/master/src/server/game/Server/Protocol/Opcodes.cpp#L160

The opcodes are located here

**Comment by Bodeguero** [comment]
@wowharley So you are copying the code already ready? I thought I was doing as I do with WoWParsePacket!
I hope it does not crash the server - because each source is different from the other! And I will make the talk test it locally before sending! For we of JadeCore team can not waste time making corrections of corrections sent!

Grateful!

**Comment by wowharley** [comment]
it is tested locally as i informed you before pulled request is added, i know what i'm doing here and know the difference between both core, its not going to crash the core..

**Comment by Bodeguero** [comment]
@wowharley It's what I expect!

Thanks for your help!

:neckbeard:

**Comment by cooler-SAI** [comment]
@Bodeguero, go to Skype

**Comment by Keital** [comment]
Guys be ready to move to Visual Studio 2015, already fixed the build

**Comment by Mysterium** [comment]
N! I love VS 2013 :(

**Comment by Keital** [comment]
VS 2013 sucks believe me!!!

**Comment by wowharley** [comment]
Can we still keep it both VS2013 and VS2015 ?

**Comment by Keital** [comment]
I fixed all of them in one of my branches (Boost)

**Comment by cooler-SAI** [comment]
Agreed with both support

**Pull request merged**
