### PR TITLE
Fix opcodes issue from last commit

### PR DESCRIPTION
**Pull request by wowharley**

### CODE REVIEW

**Comment by wowharley** [comment]
this will fix the issue with the compile on the last commit

**Comment by Bodeguero** [comment]
@wowharley You are testing locally I believe, waited Travis CI system to the evaluation!

Gratful!

**Comment by wowharley** [comment]
yes i am testing it local, i have the repo on my desktop with github desktop

**Comment by wowharley** [comment]
Glad issue was resolved

**Pull request merged**
