### PR TITLE
Fix Handler channel password

### PR DESCRIPTION
**Pull request by wowharley**
Sorry guys i missed this on my last commit, i'm trying

### CODE REVIEW

**Comment by cooler-SAI** [comment]
you like a GOD)) thanks a Lot, merged

**Comment by cooler-SAI** [comment]
@wowharley , wanna join us? I can add to to repo writer

**Comment by wowharley** [comment]
that would be awesome, i'm still learning as i go but i'm catching on pretty quick.

**Comment by cooler-SAI** [comment]
@wowharley , added you, welcome)) https://github.com/JadeCore/JadeCore/invitations

**Comment by wowharley** [comment]
thank you :)

**Pull request merged**
